# Generated by Django 5.2.1 on 2025-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(default='Sin dirección', max_length=9),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='Sin Telefono', max_length=15),
        ),
    ]
