# Generated by Django 5.2.1 on 2025-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_perfil_direccion_perfil_rut_perfil_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(default='Sin RUT', max_length=9),
        ),
    ]
